# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5f6ecd95-c7da-47ff-8ccc-71d71ee200a8";
      fsType = "ext4";
    };

  fileSystems."/home/joe/Backups" = 
    { device = "/dev/disk/by-uuid/b15de5bf-4916-4c00-af65-48968bbe720c";
      fsType = "ext4";
    };

  fileSystems."/home/joe/Storage" = 
    { device = "/dev/disk/by-uuid/85a14686-e005-400f-8149-aa2701c86031";
      fsType = "ext4";
      options = [
        "nofail"
        "x-systemd.device-timeout=5s"
      ];
    };

  boot.initrd.luks.devices."pool".device = "/dev/disk/by-uuid/0df767c8-9d8c-4640-a14a-5f91e6c7f086";

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/445e0f63-4514-4d5d-9584-9fd99f6ff0b0";

  fileSystems."/boot" = 
    { device = "/dev/disk/by-uuid/9BFD-4D0C";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
